### ISSUE TITLE
Wrong time entry closes edit popup

### ISSUE THREAD

**Issue by mscholl** [cismet/project-tracker#20]
If you edit a slot and enter an invalid time you are informed that the entry is not valid and the popup is closed and no duration is assigned to the slot. I would appreciate it if the popup wouldn't close but stay open so that one does not have to reopen it again. Additionally it would be nicer to have some kind of validator assigned to the text field that e.g. shows invalid durations in red color. In combination with the validator it would be cool if the OK button is not enabled as long as the time (or any other possible entry) is invalid. That way the "This value is wrong ..." popup won't show up and thus you won't have to close it again.

**Comment by dameiers** [comment]
Screenshot of the new implemented behaviour.

![bildschirmfoto vom 2013-11-28 16 33 05](https://f.cloud.github.com/assets/1785245/1640790/74c49386-5842-11e3-9f7e-db87d5ef39f1.png)
