### ISSUE TITLE
Auslieferung 28.11.2013

### ISSUE THREAD

**Issue by dameiers** [cismet/project-tracker#33]
betroffene issues:
#12  Füllen offener Zeiten für einen Task
#13 Lock-Week Button lockt falsche Woche
#20 Dialog zum editieren des Tasks wird bei falscher Zeiteingabe geschlossen
#22 Fehler in der Überstundenberechnung für Inhouse-Consultants
#23 Beschreibungsfeld in der QuickSearch ignoriert keine Präfix / Suffix Leerzeichen
#24 Default Selektion für Projekt und WPin der QuickSearch
#26 Tasks können per Drag&Drop hinzugefügt werden, obwohl WP abgelaufen ist
#27 Manche Mitarbeiter dürfen nicht auch alle Projekte billen
#28 aktueller Urlaubstag geht zweimal in die Urlaubsstatistik ein
#29 Löschen von Favourite Tasks nicht möglich wenn Scrollbar sichtbar
#30 Fill verteilt auch auf Abwesenheitstasks
#31 Modus für Fill: Füllen bis zur aktuellen Zeit, falls keine Endzeit eingetragen ist

**Comment by mscholl** [comment]
schön, noch schöner wären dazu versionsnummern und tags, labels sind schall und rauch...
